# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x08users.v1\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x10ListUsersRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2\x84\x01\n\x0cUsersService\x12\x33\n\x07GetUser\x12\x18.users.v1.GetUserRequest\x1a\x0e.users.v1.User\x12?\n\x0fListUsersStream\x12\x1a.users.v1.ListUsersRequest\x1a\x0e.users.v1.User0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=27
  _globals['_GETUSERREQUEST']._serialized_end=55
  _globals['_LISTUSERSREQUEST']._serialized_start=57
  _globals['_LISTUSERSREQUEST']._serialized_end=90
  _globals['_USER']._serialized_start=92
  _globals['_USER']._serialized_end=139
  _globals['_USERSSERVICE']._serialized_start=142
  _globals['_USERSSERVICE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
